### ISSUE TITLE
autoload bales not working

### ISSUE THREAD

**Issue by TheRealColdAutumnRain** [ddewar/FS22_UniversalAutoloadModhubAddon#33]
I can't get the autoload bales function to work on the  "Strautmann SEK 802" or "Pongepack". 
Or I don't know how to make it work, If I try a standard trailer I also get the shortcut in my hotkeys panel.
when I use a dlc trailer it doesn't even show and pressing the hotkeys does nothing.

**Comment by loki79uk** [comment]
It has to be assigned the option `isBaleTrailer=true` for the bale mode to be available.

**Comment by ddewar** [comment]
@loki79uk How have you been determining which trailers to add that config on? I might just go spam it on most trailers. Any thoughts on maybe switching the default?

**Comment by loki79uk** [comment]
It was set to require the flag because bale collection mode was an experimental idea (i.e. to introduce it gradually), and also because I don't want to see a bale mode option on trailers where I will never use bales.

Not implemented yet, but after reading this I'm planning to set `isBaleTrailer` true whenever there is also a `baleHeight` set in one of the loading areas (this should save @ddewar a lot of work!).

_Also, just a note that if you use CoursePlay, then the bale collection mode **will** be activated and used by CP for any vehicle, you only need `isBaleTrailer` to toggle it manually._

**Comment by loki79uk** [comment]
There is the side effect that certain trailers get the bale mode where they probably shouldn't (train, drop decks, etc).  They can be removed by setting `isBaleTrailer="false"`.  Do we think it is a good idea to set the bale mode this way?

**Comment by loki79uk** [comment]
Added in [this commit](https://github.com/loki79uk/FS22_UniversalAutoload/commit/624610c55e833b85adabd0d11b8419c5e53d8723).   Will be included in the next release.

**Comment by TheRealColdAutumnRain** [comment]
Can see how it works out with default enabled, but is there any info on the "IsbaleTrailer" ? Would be nice to know you can change it there :) ?

**Comment by loki79uk** [comment]
You are correct, the `isBaleTrailer` parameter still takes priority.  The default is only used when the paremeter is not supplied.

Now added to latest UAL release: https://github.com/loki79uk/FS22_UniversalAutoload/releases

**Comment by ddewar** [comment]
Closing as I believe this is fixed. Reopen if needed.
