### ISSUE TITLE
Trailer Request

### ISSUE THREAD

**Issue by RWTH-MK** [ddewar/FS22_UniversalAutoloadModhubAddon#36]
Hey,

thank you for the great work :) Could you add support for these [[1]](https://www.farming-simulator.com/mod.php?lang=en&country=en&mod_id=237603&title=fs2022) [[2]](https://www.farming-simulator.com/mod.php?lang=en&country=en&mod_id=239983&title=fs2022) trailers? 

Lastly two things: Could the list of supported mods be sorted alphabetically? Secondly the first link in the description is broken. Should it be [this](https://www.farming-simulator.com/mod.php?lang=en&country=en&mod_id=247589&title=fs2022) mod?

**Comment by ddewar** [comment]
I will work on seeing if I can get those working. I'll check out that link. I know one of those trailers was removed from modhub, so I probably grabbed the wrong link.

**Comment by ddewar** [comment]
Hey @RWTH-MK not sure if you have used this trailer enough to know, but the Goldhofer STZ-VP 3 doesn't look like it has straps on the flat bed portion. Are you asking for autoload on that part of just the upper part near the cab?

**Comment by RWTH-MK** [comment]
Upper part would be enough for me, I can do the rest by hand if I need it :)

**Comment by ddewar** [comment]
Both added to the next update. Sadly, due to lack of tension belts, I had to only configure some areas. Shown in the screenshots below. Let me know how they work!


Goldhofer STZ Special Lowloader:
![image](https://user-images.githubusercontent.com/15822357/202271995-5b13f2fb-19ff-4b8a-ba1b-fcce33d65fd1.png)

Goldhofer STZ-VP 3:
![image](https://user-images.githubusercontent.com/15822357/202272219-12cf6303-2384-4701-9bff-ad2dfad13fd5.png)


I'm working on a better way to display what mods are supported. Hopefully should fix the alphabetical part then.

**Comment by ddewar** [comment]
This release should have the trailers you requested. Let me know if you see any issues, otherwise I will close this request.

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.3
