### ISSUE TITLE
Trailer and vehicle request

### ISSUE THREAD

**Issue by judg393** [ddewar/FS22_UniversalAutoloadModhubAddon#37]
Hi buddy 

Good to see this mod still getting additions couple of requests if possible 

Trailer https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=243955&title=fs2022

And vehicle

https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=258254&title=fs2022

This has a load of options maybe just the bale back configuration and maybe the cut outs though not sure if it's worth that

**Comment by ddewar** [comment]
I'll see what I can do on both of those. Should be possible in at least some form for the Unimog.

I'll keep you updated!

**Comment by ddewar** [comment]
I believe this are both resolved in 

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.4

Let me know if you have any issues, otherwise we can close this issue.

**Comment by judg393** [comment]
Thank you as ever!

**Comment by bojanh66** [comment]
Hello sir, could you improve pallet loading on Rolland pack trailers ? Trailer is very big and it can accept much more pallets if you organize them by width, not by length.
Here is a picture for illustration, for example this red trailer (Bailey) is a smaller, but it can accept more pallets because they are organized much better.
![FarmingSimulator2022Game 2022-11-22 20-49-56](https://user-images.githubusercontent.com/32069662/203437721-468761bc-5b48-43ec-b2e1-be11c7fd82e0.png)

**Comment by ddewar** [comment]
@bojanh66 I just updated the width a bit on those trailers. Check this release:

https://github.com/ddewar/FS22_UniversalAutoloadModhubAddon/releases/tag/v1.0.0.5

**Comment by bojanh66** [comment]
It is much better now, tnx a lot.
Can you expand the space for the rear part of the trailer as well for both Rolland and Bailey (red trailer) ?
There is still space for 2 more pallets to be perfect :)
![FarmingSimulator2022Game 2022-11-23 06-32-23](https://user-images.githubusercontent.com/32069662/203476166-e25a0f75-b6ea-4b51-906b-5ce9322c6755.jpg)

**Comment by ddewar** [comment]
@bojanh66 I can take a look at that, please open up a new issue for that request, that way I can close this one and track it a little bit better

**Comment by judg393** [comment]
@ddewar you sir  are da bomb thanks fo suc h a speedy implementation
