### ISSUE TITLE
Trailer wont load big bags suddenly

### ISSUE THREAD

**Issue by bojanh66** [ddewar/FS22_UniversalAutoloadModhubAddon#47]
![FarmingSimulator2022Game 2022-12-02 10-25-59](https://user-images.githubusercontent.com/32069662/205263237-9ac0dfb0-1e6b-4421-983b-d423be87eab7.png)
![FarmingSimulator2022Game 2022-12-02 10-35-00](https://user-images.githubusercontent.com/32069662/205263259-228aa2d0-8f8e-433f-8da8-52c183a9cee4.png)
Hello, i didnt use this trailer for a few days and today it wont load big bags.

This is the trailer:
https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=228030

I even try to download again this trailer from Modhub, UA and UA Addon from github (latest versions), i also try to download from Modhub.
I have tested this on both current savegame and new fresh savegame and it doesnt work, but it works with bales.
What could went wrong ?

**Comment by loki79uk** [comment]
I'm pretty sure that this is because of a fairly recent update (since v1.2.4.5) which prevented any items from being loaded that are over the max height.  It had never noticed before, because there were no pallets/containers that were too tall, but now with the platinum dlc I noticed that some of the large items were loading above the maximum allowed height.  I will think about allowing loading for any items on trailers that are not box trailers or curtain trailers.

For now it should work if you use this in your local settings (height increased from 1.50):
```xml
        <vehicleConfiguration configFileName="FS22_Bailey_Bale_Pallet_Trailer/BPTrailer.xml" modHubId="228030">
            <loadingArea offset="0 1.08 -0.65" width="2.55" height="1.70" length="6.70" baleHeight="2.50"/>
            <options isBaleTrailer="true" enableSideLoading="true"/>
        </vehicleConfiguration>
```
